### ISSUE TITLE
Encountered a problem

### ISSUE THREAD

**Issue by fuqiang03** [hudra0/luci-app-qosmate#1]
![20240814002712](https://github.com/user-attachments/assets/3aabdc97-a466-47c4-8cc0-169469956fae)
Missing file path 'qosmate'

**Comment by fuqiang03** [comment]
function fetchLatestVersion() {
    return new Promise((resolve, reject) => {
        var xhr = new XMLHttpRequest();
        xhr.open('GET', 'https://raw.githubusercontent.com/hudra0/qosmate/main/etc/qosmate.sh', true);
        xhr.onload = function() {
            if (xhr.status === 200) {
                var match = xhr.responseText.match(/^VERSION="(.+)"/m);
                latestVersion = match ? match[1] : 'Unknown';
                resolve(latestVersion);
            } else {
                reject('Failed to fetch latest version');
            }
        };
        xhr.onerror = function() {
            reject('Network error');
        };
        xhr.send();
    });
}
连接错误信息,影响页面显示

**Comment by fuqiang03** [comment]
![20240814010625](https://github.com/user-attachments/assets/99edea63-d22a-42db-95e0-370e9f6f9109)

**Comment by hudra0** [comment]
Did you build qosmate from source?

**Comment by fuqiang03** [comment]
yes

**Comment by hudra0** [comment]
You might be missing the entire backend (init script, main script, etc.). Please avoid using the Makefile for now—it hasn’t been tested and is likely incomplete. I've just updated the README, so please follow those instructions to install QoSMate and luci-app-qosmate.

**Comment by fuqiang03** [comment]
@hudra0 
The information returned by fetchLatestVersion will affect the display of the page, even for the latest files. If the network is restricted, the returned information will control the entire page
I can solve any other problems on my own

**Comment by hudra0** [comment]
I made some changes to the UI which should help if there is no Internet connection. Please re-download everything and try again.

**Comment by fuqiang03** [comment]
@hudra0 
没有问题了

**Comment by fuqiang03** [comment]
@hudra0 
![20240922015319](https://github.com/user-attachments/assets/6684fa04-cf56-4073-9cb6-4143614d8394)
![20240922015342](https://github.com/user-attachments/assets/c8fe4ad6-eb17-4fcb-8891-00a3c545ad2d)
![20240922015443](https://github.com/user-attachments/assets/f139b6c0-2a65-4998-ae4d-380bbae43164)
Too many connections will result in an error
