### ISSUE TITLE
Rules persistent with cake qdisc

### ISSUE THREAD

**Issue by Dopam-IT** [hudra0/luci-app-qosmate#2]
Hello hudra, is there a way to completely remove the HFSC rules? Even if I set CAKE as the qdisc, I'm still getting drops like 995, etc. Any help would be appreciated. Thanks!

i would be used cake with just 2 two rules on my  firewall thanks

**Comment by hudra0** [comment]
Hey, these are the ACK Rate limit rules. You can just set `ACK Rate` to 0 under the advanced tab in the ui and the rules should be gone...

**Comment by Dopam-IT** [comment]
thanks for all i will test
