### ISSUE TITLE
Optimization suggestions for LuCI

### ISSUE THREAD

**Issue by pmkol** [hudra0/luci-app-qosmate#3]
1、Remove the duplicate functionality of Service Control and Enable in Global Settings, keeping only one of them.

2、For Version Information, it is recommended to add a 'Check Version' button to trigger version detection, rather than directly requesting the network. This approach is more user-friendly for users with poor network environments.

Thank you :D

**Comment by hudra0** [comment]
1 is done with 450dd41a7cf687942515ad6eb1833cda9ce3a970

> 2、For Version Information, it is recommended to add a 'Check Version' button to trigger version detection, rather than directly requesting the network. This approach is more user-friendly for users with poor network environments.

I believe it’s more user-friendly if the version is displayed automatically, and I hope retrieving the version won’t cause significant issues, even with poor connections. If problems do occur frequently, I’ll certainly revisit the idea.
